export const USER_ACTION_TYPES = {
    // Types for Email Sign Up
    USER_SIGNUP_START: 'USER_SIGNUP_START',
    USER_SIGNUP_SUCCESS: 'USER_SIGNUP_SUCCESS',
    USER_SIGNUP_FAILED: 'USER_SIGNUP_FAILED',

    // Types for Email Sign In
    USER_SIGNIN_START: 'USER_SIGNIN_START',
    USER_SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
    USER_SIGNIN_FAILED: 'USER_SIGNIN_FAILED',

    // Type for Resetting Authentication Error
    RESET_AUTH_ERROR: 'RESET_AUTH_ERROR',

    // Types for User Sign Out
    USER_SIGNOUT_START: 'USER_SIGNOUT_START',
    USER_SIGNOUT_SUCCESS: 'USER_SIGNOUT_SUCCESS',
    USER_SIGNOUT_FAILED: 'USER_SIGNOUT_FAILED',
    
    USER_UPDATE_PROGRESS_START: 'USER_UPDATE_PROGRESS_START',
    USER_UPDATE_PROGRESS_SUCCESS: 'USER_UPDATE_PROGRESS_SUCCESS',
    USER_UPDATE_PROGRESS_FAILED: 'USER_UPDATE_PROGRESS_FAILED',
    
    FETCH_USER_PROGRESS_START: 'FETCH_USER_PROGRESS_START',
    FETCH_USER_PROGRESS_SUCCESS: 'FETCH_USER_PROGRESS_SUCCESS',
    FETCH_USER_PROGRESS_FAILED: 'FETCH_USER_PROGRESS_FAILED',

    UPDATE_USER_PROFILE_START: 'UPDATE_USER_PROFILE_START',
    UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
    UPDATE_USER_PROFILE_FAILED: 'UPDATE_USER_PROFILE_FAILED',
    FETCH_CERTIFICATE_INFO_START: "FETCH_CERTIFICATE_INFO_START",
    FETCH_CERTIFICATE_INFO_SUCCESS: "FETCH_CERTIFICATE_INFO_SUCCESS",
    FETCH_CERTIFICATE_INFO_FAILED: "FETCH_CERTIFICATE_INFO_FAILED",

};
